/* Generated by Nim Compiler v1.7.1 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3   -I'/home/torerling/.choosenim/toolchains/nim-#devel/lib' -I/home/torerling/programming/nim/north/tests -o /home/torerling/programming/nim/north/nimcache/tests/megatest_4a8a08f09d37b73795649038408b5f33/stdlib_assertions.nim.c.o /home/torerling/programming/nim/north/nimcache/tests/megatest_4a8a08f09d37b73795649038408b5f33/stdlib_assertions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___systemZassertions_23)(NimStringDesc** dest) {
}
